### ISSUE TITLE
Downloaded GUID is all zero

### ISSUE THREAD

**Issue by xiaodongww** [RMonica/elastic_bridge#4]
Hi, thanks for your job. I have compiled your program successfully and the reconstruction program works well.

However, I find that when I run `./save_pcl`,  the saved guid file is all zeros (i.e. values in `pointcloud.corresp`).  I double-checked that I was using the patched ElasticFusion version. 

So, I read the code in `patches/guid.patch`.  Since I am not familiar with OpenGL and can not find how the guid system works. The counter `atomicGuidBuffer ` does not seems to explicit call functions like `increment` or `decrement`. So how does it count the number of surfels? Is this the reason that guid is all zeros?

Thanks for your reading. Looking forward to your reply!

**Comment by RMonica** [comment]
Hi.
I think you are right. Something is missing in that patch: there should be changes in the shaders which increment and decrement the counters.
I will try to recover the code, but I don't have much hope. Sorry.

**Comment by RMonica** [comment]
I had to rewrite some code from scratch, but now it should work.

**Comment by xiaodongww** [comment]
Thanks for your help. It really works!
