### ISSUE TITLE
Providing external frame

### ISSUE THREAD

**Issue by juandavid212** [RMonica/elastic_bridge#5]
Hello,
I'm trying to use your package, but I doubt setting the external frames. I'm using a robotic arm with a camera attached.
As far as I understand I have to set 
<param name="TF_POSE_ALWAYS" type="string" value="true" />
to allow the use of external frames, and:
<param name="TF_INPUT_WORLD_FRAME" type="string" value="BASE_TF />
<param name="TF_INPUT_CAMERA_FRAME" type="string" value="END_EFFECTOR_TF" />
In this sense, the point depth input (from the camera) is referenced to the end-effector frame (camera and end effector frames coincide) and the output of elastic fusion is referenced to the robot base (which is fixed).

Then, which frames should I put in WORLD_FRAME and CAMERA_FRAME params?

**Comment by RMonica** [comment]
Hi.

To provide external frames for camera tracking, you have to set the parameters:
TF_POSE_ALWAYS to true
TF_INPUT_WORLD_FRAME to the TF world frame
TF_INPUT_CAMERA_FRAME to the TF camera frame

**Comment by juandavid212** [comment]
Thanks for your answer. It's working now.
