### ISSUE TITLE
No devices connected.... waiting for devices to be connected

### ISSUE THREAD

**Issue by juandavid212** [RMonica/elastic_bridge#6]
Hello,
When the code is running, I'm receiving "No devices connected.... waiting for devices to be connected".
Is it normal?

[ INFO] [1654510343.145997562, 1290.093000000]: No devices connected.... waiting for devices to be connected
[ INFO] [1654510346.146169075, 1293.090000000]: No devices connected.... waiting for devices to be connected
[ INFO] [1654510349.146353463, 1296.086000000]: No devices connected.... waiting for devices to be connected
[ INFO] [1654510352.146518325, 1299.082000000]: No devices connected.... waiting for devices to be connected
[ INFO] [1654510353.877752285, 1300.812000000]: Publishing GlobalModel (during execution)
[ INFO] [1654510354.201105442, 1301.134000000]: elastic_bridge: downloading 1693 points.
[ INFO] [1654510354.202587870, 1301.136000000]: elastic_bridge: sending 1634 points.
[ INFO] [1654510354.202680281, 1301.136000000]: Published GlobalModel (during execution)
[ INFO] [1654510355.146684527, 1302.079000000]: No devices connected.... waiting for devices to be connected
[ INFO] [1654510358.146847529, 1305.076000000]: No devices connected.... waiting for devices to be connected
[ INFO] [1654510361.147019212, 1308.072000000]: No devices connected.... waiting for devices to be connected
[ INFO] [1654510364.147225838, 1311.069000000]: No devices connected.... waiting for devices to be connected

The point cloud is being published as normal, I'm only worried about this statement.

**Comment by RMonica** [comment]
You have to remove the old openni driver (for Kinect 1) from the launch file:
```
  <include file="$(find openni_launch)/launch/openni.launch">
    <arg name="depth_registration" value="true" />
  </include>
```
